### ISSUE TITLE
applying the patches

### ISSUE THREAD

**Issue by rand99** [percona/grafana-dashboards#1]
I just downloaded the source of grafana 2.6 from github releases.
compiled it on osx because there are no binaries
Tried to apply the sed patches but it didn't work

for example there is no ",function(c)" in query_ctrl.js to be replaced

are you sure you applied those sed commands on 2.6.0 ?
ill try again tomorrow

**Comment by roman-vynar** [comment]
Actually, the patch has to be applied against the compiled grafana 2.6.0. If you build from sources, I think it also requires to build assets. Once all done and started, you can patch Grafana, the resulting js should have function(c), the code itself doesn't.

**Comment by rand99** [comment]
ah I see. Thank you 👍 
That's was the problem.

also the sed command on osx is different
the solution was to install the gnu-sed
`brew installl gnu-sed`
and use **gsed** instead of **sed**

beautiful project!!
