### ISSUE TITLE
This is not issue:::Regarding Grafana for MongoDB if possible ?

### ISSUE THREAD

**Issue by zerOnepal** [percona/grafana-dashboards#7]
Thanks for making this public. :bow: 

Any thoughts(work in progress) on making of this: 
**Grafana dashboards for measuring  MongoDB performance with Prometheus** 

Recently I stumbled up this event [Open Source Monitoring for MySQL and MongoDB with Grafana and Prometheus](https://www.percona.com/live/data-performance-conference-2016/sessions/open-source-monitoring-mysql-and-mongodb-grafana-and-prometheus#description) link, but I can't find any slides or media :disappointed:

**Comment by roman-vynar** [comment]
https://github.com/Percona-Lab/grafana_mongodb_dashboards
https://github.com/percona/pmm/

**Comment by zerOnepal** [comment]
Thanks again, that's quick response.
