### ISSUE TITLE
Guys could you add your awesome dashboards to https://grafana.net/dashboards

### ISSUE THREAD

**Issue by Savemech** [percona/grafana-dashboards#9]
Or if you lacking of time, i can do this for you.

**Comment by roman-vynar** [comment]
The dashboards rely on Grafana patch which comes with Grafana version 4 and it is not released yet.
Also one thing is to upload dashboards, another is to keep re-uploading to maintain updates.

**Comment by Savemech** [comment]
Yes, of course, so would you discuss this topic internally and decide to keep these dashboards at grafana up-to-date? That would be awesome!
